# Assignment 1 — Python Fundamentals & NumPy

**Course:** Introduction to Data Science / Scientific Computing
**Topics:** Core Python, NumPy arrays, vectorization, broadcasting, linear algebra
**Total marks:** 50
**Time guideline:** 3–4 hours

---

### Instructions
1. Write your solution in the empty code cell directly **below each problem**.
2. Do **not** rename or delete the problem cells.
3. Your code must **run top to bottom without errors** (use *Kernel → Restart & Run All* before submitting).
4. Where a function is asked for, match the **exact function name and signature** given.
5. Comments explaining your logic are encouraged and count toward partial credit.
6. Submit this completed `.ipynb` file. Name it `assignment1_<your_name>.ipynb`.

> **Allowed imports:** only `numpy` (and the Python standard library). Do **not** use `pandas` for this assignment.


In [1]:
# Run this cell first
import numpy as np
print("NumPy version:", np.__version__)



NumPy version: 1.26.4


---
# Part A — Python Fundamentals  *(15 marks)*

No NumPy in this section. Plain Python only.

### A1. Temperature converter  *(2 marks)*

Write a function `c_to_f(celsius)` that converts a temperature in Celsius to Fahrenheit
using the formula `F = C * 9/5 + 32`.

- It should work for a single number **and** for a list of numbers (return a list in that case).

```python
c_to_f(0)          # -> 32.0
c_to_f(100)        # -> 212.0
c_to_f([0, 37, 100])  # -> [32.0, 98.6, 212.0]
```

In [8]:
def c_to_f(c_list):
    con_list = []
    for C in c_list:
        F = C * 9/5 + 32
        con_list.append(F)
    return con_list

f = c_to_f([0, 37, 100])
f

[32.0, 98.6, 212.0]

### A2. FizzBuzz with a twist  *(3 marks)*

Write a function `fizzbuzz(n)` that returns a **list** of length `n` (covering numbers `1..n`) where:
- multiples of 3 are replaced by `"Fizz"`
- multiples of 5 are replaced by `"Buzz"`
- multiples of both 3 and 5 are replaced by `"FizzBuzz"`
- all other numbers stay as integers.

```python
fizzbuzz(5)  # -> [1, 2, 'Fizz', 4, 'Buzz']
```

In [9]:
# A2 — your solution here

def fizzbuzz(n):
    return ["FizzBuzz" if i % 15 == 0 else "Fizz" if i % 3 == 0 else "Buzz" if i % 5 == 0 else i for i in range(1, n + 1)]

print(fizzbuzz(15))


[1, 2, 'Fizz', 4, 'Buzz', 'Fizz', 7, 8, 'Fizz', 'Buzz', 11, 'Fizz', 13, 14, 'FizzBuzz']


### A3. Word frequency counter  *(4 marks)*

Write a function `word_count(text)` that takes a string and returns a **dictionary** mapping each
lowercase word to the number of times it appears. Ignore case and strip basic punctuation (`. , ! ?`).

```python
word_count("The cat sat. The cat ran!")
# -> {'the': 2, 'cat': 2, 'sat': 1, 'ran': 1}
```

In [11]:
# A3 — your solution here

def word_count(text):
    words = text.split()
    word_count = {}
    for word in words:
        if word in word_count:
            word_count[word] += 1
        else:
            word_count[word] = 1
    return word_count

word_count("The cat sat. The cat ran!")

{'The': 2, 'cat': 2, 'sat.': 1, 'ran!': 1}

### A4. Filter and transform  *(3 marks)*

Given a list of integers, write a function `squares_of_evens(nums)` that returns a new list
containing the **squares of only the even numbers**, preserving order. Use a **list comprehension**.

```python
squares_of_evens([1, 2, 3, 4, 5, 6])  # -> [4, 16, 36]
```

In [1]:
# A4 — your solution here

def squares_of_evens(nums):

  squares_of_evens = []
  for a in nums:
    if a%2 ==0:
      squares_of_evens.append(a**2)
  return squares_of_evens

squares_of_evens([1,2,3,4,5,6,7,8,9,10])

[4, 16, 36, 64, 100]

### A5. Running maximum  *(3 marks)*

Write a function `running_max(nums)` that returns a list where the element at index `i` is the
maximum of `nums[0..i]`. Solve it with a plain loop (no NumPy, no `max()` over slices).

```python
running_max([3, 1, 4, 1, 5, 9, 2, 6])  # -> [3, 3, 4, 4, 5, 9, 9, 9]
```

In [2]:
# A5 — your solution here
def running_max(nums):

  max_nums = []
  max_num = nums[0]

  for num in nums:
    if num > max_num:
      max_num = num
    max_nums.append(max_num)
  return max_nums


running_max([3, 1, 4, 1, 5, 9, 2, 6])


[3, 3, 4, 4, 5, 9, 9, 9]

---
# Part B — NumPy Core  *(25 marks)*

From here on, prefer **vectorized NumPy operations** over Python loops unless a loop is explicitly allowed.

### B1. Array creation  *(3 marks)*

Create and print the following arrays. Assign each to the variable name shown.

1. `a` — a 1-D array of the integers from 10 to 20 **inclusive**.
2. `b` — a 3×3 array of all ones, dtype `float`.
3. `c` — a 1-D array of 9 values **evenly spaced** between 0 and 1 (inclusive of both ends).
4. `d` — a 4×4 identity matrix.

In [9]:
# B1 — your solution here


import numpy as np

a = np.arange(10, 21)
print(a)


b = np.ones((3, 3), dtype=float)
print(b)

c = np.linspace(0,1,9)
print(np.array(c))



d = np.eye(4)
print(d)


[10 11 12 13 14 15 16 17 18 19 20]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
print(f" Dimensions and shape of the matrix d:",np.ndim(d),"&",np.shape(d))

 Dimensions and shape of the matrix d: 2 & (4, 4)


### B2. Indexing & slicing  *(4 marks)*

Given the array `M` below, use slicing/indexing (no loops) to produce:

1. `r2` — the **third row**.
2. `last_col` — the **last column**.
3. `block` — the top-left **2×2** sub-matrix.
4. `every_other` — every other element of the **flattened** array (elements 0, 2, 4, ...).

In [12]:
#M = np.arange(1, 26).reshape(5, 5)
#print(M)

# B2 — your solution here

M = np.arange(1, 26).reshape(5, 5)
print(M)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [14]:
M[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
np.column_stack((M[:,4]))

array([[ 5, 10, 15, 20, 25]])

In [18]:
block = M[0:2, 0:2]
block

array([[1, 2],
       [6, 7]])

In [16]:
M.flatten()[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

### B3. Loops vs vectorization  *(4 marks)*

You are given `x = np.arange(1, 1_000_001)`.

1. Write a function `sum_of_squares_loop(x)` that computes the sum of squares using a **Python `for` loop**.
2. Write a function `sum_of_squares_vec(x)` that computes the same thing using **vectorized NumPy**.
3. Confirm both give the same result.
4. Use `%timeit` (or `time`) to compare their speed and briefly comment in a comment line on what you observe.

In [38]:

# B3 — your solution here


import numpy as np

x = np.arange(1, 1_000_001)

def sum_of_squares_loop(arr):
    sum_squares = 0
    for a in arr:
        if a % 2 == 0:
            sum_squares += int(a)**2
    return sum_squares

print(sum_of_squares_loop(x))



166667166667000000


In [43]:
import numpy as np

x = np.arange(1, 1_000_001)

def sum_of_squares_vec(arr):
    
    evens = arr[arr % 2 == 0]
  
    return np.sum(evens.astype(np.float64) ** 2)

print(sum_of_squares_vec(x))



1.66667166667e+17


In [44]:
sum_of_squares_loop(x) - sum_of_squares_vec(x)


0.0

In [45]:

print("Timing loop function:")
%timeit sum_of_squares_loop(x)

print("\nTiming vectorized function:")
%timeit sum_of_squares_vec(x)


Timing loop function:
285 ms ± 3.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Timing vectorized function:
7.79 ms ± 206 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### B4. Aggregations along an axis  *(4 marks)*

Given a 2-D array `scores` of shape (5 students, 4 subjects):

1. `student_avg` — each student's average score (length-5 array).
2. `subject_max` — the highest score in each subject (length-4 array).
3. `top_student` — the **index** of the student with the highest total.
4. `overall_std` — the standard deviation of all scores.

In [46]:

# B4 — your solution here
import numpy as np

# Initialize the array based on your prompt
rng = np.random.default_rng(42)
scores = rng.integers(40, 101, size=(5, 4))
print("Scores Matrix:")
print(scores)

# 1. Each student's average score (mean across columns)
student_avg = np.mean(scores, axis=1)

# 2. The highest score in each subject (max down rows)
subject_max = np.max(scores, axis=0)

# 3. The index of the student with the highest total marks
top_student = np.argmax(np.sum(scores, axis=1))

# 4. The standard deviation of all scores combined
overall_std = np.std(scores)

# Displaying Results
print("\n--- Results ---")
print("student_avg :", student_avg)
print("subject_max :", subject_max)
print("top_student :", top_student)
print(f"overall_std : {overall_std:.4f}")


Scores Matrix:
[[45 87 79 66]
 [66 92 45 82]
 [52 45 72 99]
 [84 86 83 87]
 [71 47 91 67]]

--- Results ---
student_avg : [69.25 71.25 67.   85.   69.  ]
subject_max : [84 92 91 99]
top_student : 3
overall_std : 17.1146


### B5. Boolean masking  *(4 marks)*

Using the `scores` array from B4:

1. `passing` — a boolean array, `True` where score >= 60.
2. `num_passing` — total count of passing scores.
3. `high_scores` — a 1-D array of all scores strictly greater than 90.
4. Replace every score below 50 with 50 (a "grade floor"), storing the result in `floored` **without modifying** `scores`.

In [47]:
# B5 — your solution here


import numpy as np

# Setting up the matrix from B4
rng = np.random.default_rng(42)
scores = rng.integers(40, 101, size=(5, 4))

# 1. passing — a boolean array, True where score >= 60
passing = scores >= 60

# 2. num_passing — total count of passing scores
num_passing = np.sum(passing)

# 3. high_scores — a 1-D array of all scores strictly greater than 90
high_scores = scores[scores > 90]

# 4. Create floored without modifying the original scores matrix
floored = np.where(scores < 50, 50, scores)

# Displaying Results
print("Original Scores:\n", scores)
print("\npassing:\n", passing)
print("\nnum_passing:", num_passing)
print("\nhigh_scores:", high_scores)
print("\nfloored:\n", floored)


Original Scores:
 [[45 87 79 66]
 [66 92 45 82]
 [52 45 72 99]
 [84 86 83 87]
 [71 47 91 67]]

passing:
 [[False  True  True  True]
 [ True  True False  True]
 [False False  True  True]
 [ True  True  True  True]
 [ True False  True  True]]

num_passing: 15

high_scores: [92 99 91]

floored:
 [[50 87 79 66]
 [66 92 50 82]
 [52 50 72 99]
 [84 86 83 87]
 [71 50 91 67]]


In [48]:
## Another Example 

students =  np.array(["ram","hari","madhu","pawan","kalyan"])
subjects  = np.array(["maths","physics","chemistry","geophyics"])

marks = np.array([[80,88,74,85],
                    [78,25,90,87],
                    [85,92,90,90],
                    [80,82,90,91],
                    [90,85,82,83]])



students_avg = np.mean(marks, axis = 1)

for name , avg in zip(students, students_avg):
    print(f"The average marks of {name} is {avg}")

The average marks of ram is 81.75
The average marks of hari is 70.0
The average marks of madhu is 89.25
The average marks of pawan is 85.75
The average marks of kalyan is 85.0


In [49]:
Max_marks  = np.max(marks, axis = 0)

for sub,mar in zip(subjects, Max_marks):
  print(f" Highest score in each subject is {sub} & marks is {mar}")


 Highest score in each subject is maths & marks is 90
 Highest score in each subject is physics & marks is 92
 Highest score in each subject is chemistry & marks is 90
 Highest score in each subject is geophyics & marks is 91


In [50]:

total_marks_per_student = np.sum(marks, axis=1)

top_student = ""
total = 300
for stu, max_marks in zip(students, total_marks_per_student):
    if max_marks > total:
        total = max_marks
        top_student = stu

print(f"The student {top_student} got the highest marks {total}")



The student madhu got the highest marks 357


In [51]:
total_marks_per_student

array([327, 280, 357, 343, 340])

In [52]:
std_dev = np.std(total_marks_per_student)
total_marks_per_student
std_dev


26.477159968546474

In [54]:

marks = np.array([[80,88,74,85],
                    [78,25,90,87],
                    [85,92,90,90],
                    [80,82,90,91],
                    [90,85,82,83]])

passing = marks >= 60
print(passing)
print(np.sum(passing))


[[ True  True  True  True]
 [ True False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
19


In [55]:
above_90 = marks[marks > 90]
above_90

array([92, 91])

In [57]:

floored = np.where(marks < 50, 50, marks)
floored,marks


(array([[80, 88, 74, 85],
        [78, 50, 90, 87],
        [85, 92, 90, 90],
        [80, 82, 90, 91],
        [90, 85, 82, 83]]),
 array([[80, 88, 74, 85],
        [78, 25, 90, 87],
        [85, 92, 90, 90],
        [80, 82, 90, 91],
        [90, 85, 82, 83]]))

### B6. Reshaping & broadcasting  *(3 marks)*

1. Take `np.arange(12)` and reshape it into a 3×4 array called `grid`.
2. Create a 1-D array `col_weights = np.array([1, 2, 3, 4])` and multiply each **column** of `grid`
   by the corresponding weight using **broadcasting** (no loops). Store as `weighted`.
3. Subtract the **row mean** from each element so every row of `centered` has mean 0.

In [59]:
# B6 — your solution here
grid = np.arange(12)
grid

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
import numpy as np


grid = np.arange(12).reshape(3, 4)
print("Original grid:\n", grid)

col_weights = np.array([1, 2, 3, 4])
weighted = grid * col_weights
print("\nWeighted grid:\n", weighted)

row_means = np.mean(weighted, axis=1, keepdims=True)
centered = weighted - row_means
print("\nCentered grid:\n", centered)


print("\nRow means of centered matrix:", np.mean(centered, axis=1))


Original grid:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Weighted grid:
 [[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]]

Centered grid:
 [[ -5.  -3.   1.   7.]
 [-11.  -5.   3.  13.]
 [-17.  -7.   5.  19.]]

Row means of centered matrix: [0. 0. 0.]


### B7. Linear algebra  *(3 marks)*

Solve the system of linear equations:

```
2x +  y -  z =  8
-3x - y + 2z = -11
-2x + y + 2z =  -3
```

1. Build the coefficient matrix `A` and the right-hand side vector `b`.
2. Solve for `[x, y, z]` using `np.linalg.solve` and store as `solution`.
3. Verify by computing `A @ solution` and comparing to `b` (use `np.allclose`).

In [73]:
# B7 — your solution here
A = np.array([[2,1,-1],
              [-3,-1,2],
              [-2,1,2]])

b = np.array([8,-11,-3])

sol = np.linalg.solve(A,b)

In [74]:
print(f"\nx = {sol[0]:.2f}")
print(f"y = {sol[1]:.2f}")
print(f"z = {sol[2]:.2f}")


x = 2.00
y = 3.00
z = -1.00


---
# Part C — Applied Mini-Problem  *(10 marks)*

### C1. Monte Carlo estimate of π  *(6 marks)*

You can estimate π by throwing random darts at a unit square `[0,1] x [0,1]` and counting how many
land inside the quarter circle of radius 1 centered at the origin. The fraction inside, times 4,
approximates π.

Write a function `estimate_pi(n, seed=0)` that:
1. Generates `n` random `(x, y)` points in the unit square using a seeded `np.random.default_rng`.
2. Counts how many fall inside the quarter circle (`x**2 + y**2 <= 1`) — **vectorized, no loops**.
3. Returns the estimate of π as a float.

Then call it with `n = 1_000_000` and print your estimate alongside `np.pi`.

In [79]:
# C1 — your solution here
import numpy as np

def estimate_pi(n, seed=0):
    #  Initialize the seeded random number generator
    rng = np.random.default_rng(seed)

    #  Generate n random coordinates for x and y between 0 and 1
    x = rng.random(n)
    y = rng.random(n)

    #  Use the quarter circle condition to create a boolean mask
    inside_quarter_circle = (x**2 + y**2) <= 1

    # Sum up the True values and multiply the fraction by 4

    pi_estimate = 4 * np.sum(inside_quarter_circle) / n

    return float(pi_estimate)

# Call the function with 1,000,000 points

n_samples = 1_000_000
my_estimate = estimate_pi(n_samples)

print(f"\nMy Estimate : {my_estimate}")
print(f"NumPy's Pi  : {np.pi}")
print(f"Difference  : {abs(np.pi - my_estimate):.6f}")



My Estimate : 3.141368
NumPy's Pi  : 3.141592653589793
Difference  : 0.000225


### C2. Short reflection  *(4 marks)*

In the markdown cell below, answer in 3–5 sentences:

1. Why is the vectorized NumPy version in B3 so much faster than the Python loop?
2. How does the accuracy of your π estimate in C1 change as `n` grows, and why?

*Write your answer here (double-click to edit).*

1. 

2. 

---
### Before you submit — checklist
- [ ] Restart kernel and *Run All* — no errors.
- [ ] All function names and signatures match the spec exactly.
- [ ] No use of `pandas`; only `numpy` and the standard library.
- [ ] File renamed to `assignment1_<your_name>.ipynb`.

*Good luck!*